package appconstants

// This package provides constants used throughout this app

// System constants
const EXIT_FAILURE int = 125
const EXIT_CLEAN int = 0

// App constants
const CONFIG_FILE_PATH string = "./config.dat"

// Message constants
const STARTUP_MSG string = "System Starting"
const SIMULATION_COMPLETE_MSG string = "Simulation Complete"
const SIMULATION_FAILED_MSG string = "Simulation Failed - Please see log for details!"
const ITEM_NOT_FOUND string = "Item Not Found"

// Simulator constants
const DEFAULT_SVC_WAIT int = 10

// Data Point Type constants
const DATA_POINT_TYPE_RANGED int = 1
const DATA_POINT_TYPE_BOOLEAN int = 2
const DATA_POINT_TYPE_CALCULATED int = 3
const DATA_POINT_TYPE_INFORMATIONAL int = 4

// Sensor constants
const SENSOR_STATE_CURRENT int = 0
const SENSOR_STATE_PREVIOUS int = 1

// Tranportation Mode Constants
const TRANSPORT_MODE_SHIP int = 1
const TRANSPORT_MODE_PLANE int = 2
const TRANSPORT_MODE_TRUCK int = 3
const TRANSPORT_MODE_FALCON int = 4
const TRANSPORT_MODE_DRAGON int = 5
const TRANSPORT_MODE_TRAIN int = 6

// Sensor Type Description Contants
const SENSOR_TYPE_ALTIMETER string = "altimeter"
const SENSOR_TYPE_BATTERY string = "battery"
const SENSOR_TYPE_COMPUTE string = "compute"
const SENSOR_TYPE_GEIGER string = "geiger counter"
const SENSOR_TYPE_GPS string = "gps"
const SENSOR_TYPE_GYRO string = "gyroscopic positioning"
const SENSOR_TYPE_LOCK string = "lock state"
const SENSOR_TYPE_MOTION string = "motion sensor"
const SENSOR_TYPE_RADIO string = "radio"
const SENSOR_TYPE_SEAL string = "door seal"
const SENSOR_TYPE_SPECTROMETER string = "spectrometer"
const SENSOR_TYPE_TEMPHUMIDITY string = "temperature and barometric"
const SENSOR_TYPE_FIRE string = "fire"

// Sensor Type ID Contants
const SENSOR_TYPE_ID_ALTIMETER int = 1
const SENSOR_TYPE_ID_BATTERY int = 2
const SENSOR_TYPE_ID_COMPUTE int = 3
const SENSOR_TYPE_ID_GEIGER int = 4
const SENSOR_TYPE_ID_GPS int = 5
const SENSOR_TYPE_ID_GYRO int = 6
const SENSOR_TYPE_ID_LOCK int = 7
const SENSOR_TYPE_ID_MOTION int = 8
const SENSOR_TYPE_ID_RADIO int = 9
const SENSOR_TYPE_ID_SEAL int = 10
const SENSOR_TYPE_ID_SPECTROMETER int = 11
const SENSOR_TYPE_ID_TEMPHUMIDITY int = 12
const SENSOR_TYPE_ID_FIRE int = 13

// Sensor Data Point Constants
const SENSOR_DATA_POINT_BATTERY_MAX_AMP_HOURS int = 1
const SENSOR_DATA_POINT_BATTERY_REMAINING_AMP_HOURS int = 2
const SENSOR_DATA_POINT_BATTERY_DRAIN_RATE int = 3
const SENSOR_DATA_POINT_BATTERY_CAPACITANCE_GEL_EXPECTED_VOLUME int = 4
const SENSOR_DATA_POINT_BATTERY_CAPACITANCE_GEL_ACTUAL_VOLUME int = 5
const SENSOR_DATA_POINT_BATTERY_BATTERY_TEMPERATURE int = 6
const SENSOR_DATA_POINT_BATTERY_BATTERY_SENSOR_STATE int = 7
const SENSOR_DATA_POINT_BATTERY_BATTERY_CHARGE_PCT int = 8
const SENSOR_DATA_POINT_RADIO_RADIO_SENSOR_STATE int = 9
const SENSOR_DATA_POINT_RADIO_RADIO_POWER_STATE int = 10
const SENSOR_DATA_POINT_RADIO_RADIO_FIRMWARE_STATE int = 11
const SENSOR_DATA_POINT_RADIO_RADIO_FIRMWARE_VERSION int = 12
const SENSOR_DATA_POINT_RADIO_RADIO_SIGNAL_STRENGTH int = 13
const SENSOR_DATA_POINT_RADIO_GPS_SIGNAL_STRENGTH int = 14
const SENSOR_DATA_POINT_RADIO_LOCAL_WIFI_SIGNAL_STRENGTH int = 15
const SENSOR_DATA_POINT_RADIO_GPS_HANDSHAKE_STABLE int = 16
const SENSOR_DATA_POINT_RADIO_LOCAL_WIFI_HANDSHAKE int = 17
const SENSOR_DATA_POINT_RADIO_WIFI_UPLINK_STATE int = 18
const SENSOR_DATA_POINT_RADIO_WIFI_DOWNLINK_STATE int = 19
const SENSOR_DATA_POINT_RADIO_WIFI_DOWNLOAD_SPEED int = 20
const SENSOR_DATA_POINT_RADIO_WIFI_UPLOAD_SPEED int = 21
const SENSOR_DATA_POINT_TEMPANDHUMIDITY_OVERALL_INTERNAL_TEMPERATURE int = 22
const SENSOR_DATA_POINT_TEMPANDHUMIDITY_TEMPERATURE_SENSOR_STATE int = 23
const SENSOR_DATA_POINT_TEMPANDHUMIDITY_BAROMETRIC_SENSOR_STATE int = 24
const SENSOR_DATA_POINT_TEMPANDHUMIDITY_HUMIDITY_LEVEL int = 25
const SENSOR_DATA_POINT_TEMPANDHUMIDITY_MOISTURE_LEVEL int = 130
const SENSOR_DATA_POINT_GYROSCOPIC_X_AXIS_ANGLE int = 26
const SENSOR_DATA_POINT_GYROSCOPIC_Y_AXIS_ANGLE int = 27
const SENSOR_DATA_POINT_GYROSCOPIC_Z_AXIS_ANGLE int = 28
const SENSOR_DATA_POINT_GYROSCOPIC_GYROSCOPIC_SENSOR_STATE int = 29
const SENSOR_DATA_POINT_GPS_EXPECTED_GPS_POSITION int = 30
const SENSOR_DATA_POINT_GPS_ACTUAL_GPS_POSITION int = 31
const SENSOR_DATA_POINT_GPS_GPS_SENSOR_STATE int = 32
const SENSOR_DATA_POINT_COMPUTE_CPU_UTILIZATION int = 33
const SENSOR_DATA_POINT_COMPUTE_NUM_CPU_CORES int = 34
const SENSOR_DATA_POINT_COMPUTE_TOTAL_AMOUNT_OF_MEMORY int = 35
const SENSOR_DATA_POINT_COMPUTE_AMOUNT_MEMORY_USED int = 36
const SENSOR_DATA_POINT_COMPUTE_MEMORY_UTILIZATION int = 37
const SENSOR_DATA_POINT_COMPUTE_TOTAL_DISK_STORAGE int = 38
const SENSOR_DATA_POINT_COMPUTE_REMAINING_DISK_STORAGE int = 39
const SENSOR_DATA_POINT_COMPUTE_COMPUTE_SENSOR_STATE int = 40
const SENSOR_DATA_POINT_COMPUTE_COMPUTE_FIRMWARE_STATE int = 41
const SENSOR_DATA_POINT_COMPUTE_COMPUTE_FIRMWARE_VERSION int = 42
const SENSOR_DATA_POINT_COMPUTE_OS_TYPE_VERSION int = 43
const SENSOR_DATA_POINT_ALTIMETER_ALTIMETER_STATE int = 44
const SENSOR_DATA_POINT_ALTIMETER_ALTITUDE_TRUCK int = 45
const SENSOR_DATA_POINT_ALTIMETER_ALTITUDE_TRAIN int = 46
const SENSOR_DATA_POINT_ALTIMETER_ALTITUDE_SHIP int = 47
const SENSOR_DATA_POINT_ALTIMETER_ALTITUDE_PLANE int = 48
const SENSOR_DATA_POINT_ALTIMETER_ALTITUDE_FALCON int = 49
const SENSOR_DATA_POINT_ALTIMETER_ALTITUDE_DRAGON int = 50
const SENSOR_DATA_POINT_LOCK_LOCK_STATE int = 51
const SENSOR_DATA_POINT_LOCK_LOCK_TIME int = 52
const SENSOR_DATA_POINT_LOCK_LOCK_EVENT_METHOD int = 53
const SENSOR_DATA_POINT_LOCK_LOCK_EVENT_TYPE int = 54
const SENSOR_DATA_POINT_SPECTROMETER_SPECTROMETER_STATE int = 55
const SENSOR_DATA_POINT_SPECTROMETER_LITHIUM int = 56
const SENSOR_DATA_POINT_SPECTROMETER_LITHIUM_AEROSOLS int = 57
const SENSOR_DATA_POINT_SPECTROMETER_HELIUM int = 58
const SENSOR_DATA_POINT_SPECTROMETER_NEON int = 59
const SENSOR_DATA_POINT_SPECTROMETER_ARGON int = 60
const SENSOR_DATA_POINT_SPECTROMETER_KRYPTON int = 61
const SENSOR_DATA_POINT_SPECTROMETER_XENON int = 62
const SENSOR_DATA_POINT_SPECTROMETER_RADON int = 63
const SENSOR_DATA_POINT_SPECTROMETER_OGANESSON int = 64
const SENSOR_DATA_POINT_SPECTROMETER_CARBON_DIOXIDE int = 65
const SENSOR_DATA_POINT_SPECTROMETER_CARBON_MONOXIDE int = 66
const SENSOR_DATA_POINT_SPECTROMETER_PROPANE int = 67
const SENSOR_DATA_POINT_SPECTROMETER_ACETYLENE int = 68
const SENSOR_DATA_POINT_SPECTROMETER_HYDROGEN int = 69
const SENSOR_DATA_POINT_SPECTROMETER_NITROGEN int = 70
const SENSOR_DATA_POINT_SPECTROMETER_OXYGEN int = 71
const SENSOR_DATA_POINT_SPECTROMETER_PETROLEUM int = 72
const SENSOR_DATA_POINT_SPECTROMETER_METHANE int = 73
const SENSOR_DATA_POINT_SPECTROMETER_ETHANE int = 74
const SENSOR_DATA_POINT_SPECTROMETER_BUTANE int = 75
const SENSOR_DATA_POINT_SPECTROMETER_PENTANE int = 76
const SENSOR_DATA_POINT_SPECTROMETER_HEXANE int = 77
const SENSOR_DATA_POINT_SPECTROMETER_CARBON int = 78
const SENSOR_DATA_POINT_SPECTROMETER_SULFUR int = 79
const SENSOR_DATA_POINT_SPECTROMETER_POTASSIUM_NITRATE int = 80
const SENSOR_DATA_POINT_SPECTROMETER_URANIUM int = 81
const SENSOR_DATA_POINT_SPECTROMETER_PLUTONIUM int = 82
const SENSOR_DATA_POINT_SPECTROMETER_BERYLLIUM int = 83
const SENSOR_DATA_POINT_SPECTROMETER_BORON int = 84
const SENSOR_DATA_POINT_SPECTROMETER_FLUORINE int = 85
const SENSOR_DATA_POINT_SPECTROMETER_SODIUM int = 86
const SENSOR_DATA_POINT_SPECTROMETER_MAGNESIUM int = 87
const SENSOR_DATA_POINT_SPECTROMETER_ALUMINUM int = 88
const SENSOR_DATA_POINT_SPECTROMETER_SILICON int = 89
const SENSOR_DATA_POINT_SPECTROMETER_PHOSPHORUS int = 90
const SENSOR_DATA_POINT_SPECTROMETER_CHLORINE int = 91
const SENSOR_DATA_POINT_SPECTROMETER_POTASSIUM int = 92
const SENSOR_DATA_POINT_SPECTROMETER_CALCIUM int = 93
const SENSOR_DATA_POINT_SPECTROMETER_SCANDIUM int = 94
const SENSOR_DATA_POINT_SPECTROMETER_TITANIUM int = 95
const SENSOR_DATA_POINT_SPECTROMETER_VANADIUM int = 96
const SENSOR_DATA_POINT_SPECTROMETER_CHROMIUM int = 97
const SENSOR_DATA_POINT_SPECTROMETER_MANGANESE int = 98
const SENSOR_DATA_POINT_SPECTROMETER_IRON int = 99
const SENSOR_DATA_POINT_SPECTROMETER_COBALT int = 100
const SENSOR_DATA_POINT_SPECTROMETER_NICKEL int = 101
const SENSOR_DATA_POINT_SPECTROMETER_COPPER int = 102
const SENSOR_DATA_POINT_SPECTROMETER_ZINC int = 103
const SENSOR_DATA_POINT_SPECTROMETER_GALLIUM int = 104
const SENSOR_DATA_POINT_SPECTROMETER_GERMANIUM int = 105
const SENSOR_DATA_POINT_SPECTROMETER_ARSENIC int = 106
const SENSOR_DATA_POINT_SPECTROMETER_SELENIUM int = 107
const SENSOR_DATA_POINT_SPECTROMETER_BROMINE int = 108
const SENSOR_DATA_POINT_SPECTROMETER_RUBIDIUM int = 109
const SENSOR_DATA_POINT_SPECTROMETER_STRONTIUM int = 110
const SENSOR_DATA_POINT_SPECTROMETER_YTTRIUM int = 111
const SENSOR_DATA_POINT_SPECTROMETER_PALLADIUM int = 112
const SENSOR_DATA_POINT_SPECTROMETER_SILVER int = 113
const SENSOR_DATA_POINT_SPECTROMETER_LEAD int = 114
const SENSOR_DATA_POINT_SPECTROMETER_THORIUM int = 115
const SENSOR_DATA_POINT_SPECTROMETER_OPOCS int = 116
const SENSOR_DATA_POINT_SPECTROMETER_EXPLOSIVES int = 117
const SENSOR_DATA_POINT_SPECTROMETER_URATES int = 118
const SENSOR_DATA_POINT_SPECTROMETER_WGNM int = 119
const SENSOR_DATA_POINT_MOTION_MOTIONSENSORSTATE int = 120
const SENSOR_DATA_POINT_MOTION_NUMBEROFCONTACTS int = 121
const SENSOR_DATA_POINT_MOTION_AVERAGEVELOCITY int = 122
const SENSOR_DATA_POINT_GEIGER_GEIGERCOUNTERSTATE int = 123
const SENSOR_DATA_POINT_GEIGER_GEIGERREADING int = 124
const SENSOR_DATA_POINT_SEALSTATE_SEALSENSORSTATE int = 125
const SENSOR_DATA_POINT_SEALSTATE_SEALSTATE int = 126
const SENSOR_DATA_POINT_FIRE_FIRESENSORSTATE int = 127
const SENSOR_DATA_POINT_FIRE_FIREDETECTED int = 128
const SENSOR_DATA_POINT_FIRE_FIRESUPPRESSIONSTATE int = 129
